


import { Language, TierLevel, PricingTier, TranslateFn } from './types';

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {
    appName: "SnapifY",
    heroTitlePrefix: "Relive the Magic,",
    heroTitleSuffix: "Forever Yours",
    heroDesc: "Create shared albums for birthdays, weddings, and parties in seconds. Let your guests capture the magic with AI-enhanced organization.",
    getStarted: "Get Started",
    adminDemo: "Admin Demo",
    signIn: "Sign In",
    signUp: "Sign Up",
    fullName: "Full Name",
    email: "Email Address",
    password: "Password",
    createAccount: "Create Account",
    continueGoogle: "Continue with Google",
    terms: "By continuing, you agree to our Terms & Conditions",
    pricingTitle: "Simple, Transparent Pricing",
    bestValue: "Best Value",
    forProfessionals: "For Professionals",
    event: "event",
    currentPlan: "Current Plan",
    contactSales: "Contact Sales",
    startFree: "Start for Free",
    myEvents: "My Events",
    manageEvents: "Manage your parties and albums",
    newEvent: "New Event",
    noEvents: "No events yet",
    createFirst: "Create your first event to start snapping memories with friends!",
    createNow: "Create an event now",
    dateTBD: "Date TBD",
    memories: "memories",
    owner: "Owner",
    expired: "Expired",
    active: "Active",
    forever: "Forever",
    copyLink: "Copy Link",
    hostedBy: "Hosted by",
    gallery: "Gallery",
    noPhotos: "No photos yet",
    beFirst: "Be the first to snap a moment!",
    snap: "Snap",
    upload: "Upload",
    joinParty: "Join the Party",
    enterName: "Enter your name to contribute photos",
    yourName: "Your Name",
    continue: "Continue",
    cancel: "Cancel",
    createEvent: "Create New Event",
    eventTitle: "Event Title",
    eventTheme: "Event Theme",
    eventDate: "Event Date",
    setDate: "Set Date",
    aiDesc: "AI Description",
    autoGenerate: "Auto-Generate",
    generating: "Generating...",
    aiPlaceholder: "Click auto-generate to let AI write a fun description...",
    createParty: "Create Party",
    guest: "Guest",
    logOut: "Log Out",
    home: "Home",
    adminDashboard: "SnapifY Admin",
    masterControl: "Master Control Dashboard",
    users: "Users",
    events: "Events",
    exit: "Exit",
    totalUsers: "Total Users",
    totalEvents: "Total Events",
    totalMedia: "Total Media",
    storage: "Storage",
    registeredUsers: "Registered Users",
    tier: "Tier",
    actions: "Actions",
    deleteUserConfirm: "Are you sure you want to delete this user and all their data?",
    storageUsage: "Storage Usage by User",
    systemEvents: "System Events",
    host: "Host",
    status: "Status",
    mediaCount: "Media Count",
    items: "items",
    noDate: "No Date",
    exp: "Exp",
    unlimited: "Unlimited",
    editEvent: "Edit Event",
    modifyExpiration: "Modify Expiration",
    neverExpires: "Never Expires",
    expireImmediately: "Expire Immediately",
    setNewDuration: "Set New Duration (from now)",
    saveChanges: "Save Changes",
    modifyExpirationNote: "Modifying expiration will reset the timer starting from the moment you click Save.",
    seconds: "Seconds",
    minutes: "Minutes",
    hours: "Hours",
    days: "Days",
    managing: "Managing",
    mediaItems: "media items",
    noMedia: "No media in this event",
    deleteMediaConfirm: "Delete this item?",
    deleteEventConfirm: "Delete this event and all its media permanently?",
    cameraError: "Unable to access camera. Please check permissions.",
    takePhoto: "Take Photo",
    retry: "Retry",
    eventExpiredTitle: "Event Expired",
    eventExpiredMsg: "This event's access period has ended. The gallery is no longer accessible to the public. Contact the event organizer for more information.",
    goHome: "Go Home",
    adminModeExpired: "Admin Mode: Viewing Expired Event",
    unknownUser: "Unknown User",
    authErrorFill: "Please fill in all fields",
    authErrorEmail: "This email is already registered",
    authErrorInvalid: "Invalid credentials. Please try again.",
    linkCopied: "Link copied to clipboard!",
    salesContactMsg: "Thank you for your interest! Our sales team will contact you shortly to upgrade your plan.",
    adminSettings: "Admin Settings: Expiration",
    customDuration: "Custom Duration",
    iAmPhotographer: "I am a Photographer / Studio",
    studioName: "Studio / Business Name",
    studioDashboard: "Studio Dashboard",
    verifiedStudio: "Verified Studio",
    downloadAll: "Download All",
    views: "Views",
    watermark: "Apply Watermark",
    watermarkApplied: "Watermark will be applied",
    applyWatermark: "Apply Watermark",
    storageLimit: "Storage Limit Reached! Please upgrade to upload more.",
    videoRestricted: "Video uploads are available on Pro and Studio plans.",
    upgradeToUpload: "Upgrade to Upload",
    setCover: "Set as Cover",
    coverSet: "Cover image updated!",
    contactSalesTitle: "Contact Sales to Upgrade",
    contactSalesDesc: "To unlock this tier, please contact our sales team. An administrator will upgrade your account immediately.",
    openWhatsapp: "Open WhatsApp",
    openEmail: "Send Email",
    downloading: "Zipping...",
    downloadReady: "Download Ready",
    zipError: "Error creating zip file.",
    slideshow: "Slideshow",
    exitSlideshow: "Exit Slideshow",
    play: "Play",
    pause: "Pause",
    studioSettings: "Studio Settings",
    uploadLogo: "Upload Logo/Signature",
    logoDesc: "Upload a PNG with transparent background for best results. This will be applied to the bottom-right of all photos.",
    currentLogo: "Current Logo",
    removeLogo: "Remove Logo",
    saveSettings: "Save Settings",
    opacity: "Opacity",
    size: "Size",
    preview: "Watermark Preview",
    position: "Position",
    offsetX: "Horizontal Offset",
    offsetY: "Vertical Offset",
    topLeft: "Top Left",
    topRight: "Top Right",
    bottomLeft: "Bottom Left",
    bottomRight: "Bottom Right",
    center: "Center",
    guestbook: "Guestbook",
    leaveMessage: "Leave a message...",
    signGuestbook: "Sign Guestbook",
    noMessages: "No messages yet. Be the first!",
    messageSent: "Message sent!",
    pinRequired: "PIN Required",
    enterPin: "Enter Event PIN",
    submitPin: "Unlock Event",
    optionalPin: "Optional PIN Code",
    pinDesc: "Leave blank for public access",
    invalidPin: "Incorrect PIN",
    findMe: "Find Me",
    findMeTitle: "Find Me with AI",
    findMeDesc: "Upload a selfie and we'll highlight photos of you in this gallery.",
    uploadSelfie: "Take Selfie",
    scanning: "Scanning Gallery...",
    noFaceDetected: "No face detected in your selfie. Try again.",
    foundMatches: "Found Matches",
    noMatchesFound: "No photos of you found yet.",
    clearFilter: "Clear Filter",
    processing: "Processing Video...",
    switchCamera: "Switch Camera",
    backToApp: "Back to App"
  },
  mk: {
    appName: "SnapifY",
    heroTitlePrefix: "Забавувај се.",
    heroTitleSuffix: "Сликај веднаш.",
    heroDesc: "Креирајте заеднички албуми за родендени, свадби и забави за неколку секунди. Дозволете им на гостите да ја доловат магијата.",
    getStarted: "Започни",
    adminDemo: "Админ демо",
    signIn: "Најави се",
    signUp: "Регистрирај се",
    fullName: "Целосно име",
    email: "Е-пошта",
    password: "Лозинка",
    createAccount: "Креирај профил",
    continueGoogle: "Продолжи со Google",
    terms: "Со продолжување, се согласувате со нашите Услови",
    pricingTitle: "Едноставни цени",
    bestValue: "Најдобро",
    forProfessionals: "За професионалци",
    event: "настан",
    currentPlan: "Тековен план",
    contactSales: "Контакт",
    startFree: "Започни бесплатно",
    myEvents: "Мои настани",
    manageEvents: "Управувајте со вашите забави и албуми",
    newEvent: "Нов настан",
    noEvents: "Сè уште нема настани",
    createFirst: "Креирајте го првиот настан и сликајте спомени!",
    createNow: "Креирај настан",
    dateTBD: "Датум наскоро",
    memories: "спомени",
    owner: "Сопственик",
    expired: "Истечен",
    active: "Активен",
    forever: "Засекогаш",
    copyLink: "Копирај линк",
    hostedBy: "Организирано од",
    gallery: "Галерија",
    noPhotos: "Нема фотографии",
    beFirst: "Бидете први што ќе сликате!",
    snap: "Сликај",
    upload: "Прикачи",
    joinParty: "Придружи се",
    enterName: "Внесете го вашето име за да прикачите слики",
    yourName: "Вашето име",
    continue: "Продолжи",
    cancel: "Откажи",
    createEvent: "Креирај нов настан",
    eventTitle: "Наслов на настан",
    eventTheme: "Тема на настан",
    eventDate: "Датум на настан",
    setDate: "Постави датум",
    aiDesc: "AI Опис",
    autoGenerate: "Генерирај",
    generating: "Се генерира...",
    aiPlaceholder: "Кликни генерирај за AI да напише опис...",
    createParty: "Креирај забава",
    guest: "Гостин",
    logOut: "Одјави се",
    home: "Почетна",
    adminDashboard: "SnapifY Админ",
    masterControl: "Главен контролен панел",
    users: "Корисници",
    events: "Настани",
    exit: "Излез",
    totalUsers: "Вкупно корисници",
    totalEvents: "Вкупно настани",
    totalMedia: "Вкупно медиуми",
    storage: "Меморија",
    registeredUsers: "Регистрирани корисници",
    tier: "Ниво",
    actions: "Акции",
    deleteUserConfirm: "Дали сте сигурни дека сакате да го избришете корисникот?",
    storageUsage: "Искористеност на меморија",
    systemEvents: "Системски настани",
    host: "Домаќин",
    status: "Статус",
    mediaCount: "Број на медиуми",
    items: "ставки",
    noDate: "Без датум",
    exp: "Истекува",
    unlimited: "Неограничено",
    editEvent: "Уреди настан",
    modifyExpiration: "Промени истекување",
    neverExpires: "Никогаш не истекува",
    expireImmediately: "Истечи веднаш",
    setNewDuration: "Постави ново времетраење",
    saveChanges: "Зачувај промени",
    modifyExpirationNote: "Промената на истекување ќе го ресетира тајмерот од моментот на зачувување.",
    seconds: "Секунди",
    minutes: "Минути",
    hours: "Часови",
    days: "Денови",
    managing: "Управување",
    mediaItems: "медиумски ставки",
    noMedia: "Нема медиуми во овој настан",
    deleteMediaConfirm: "Избриши ја оваа ставка?",
    deleteEventConfirm: "Избриши го настанот трајно?",
    cameraError: "Нема пристап до камерата.",
    takePhoto: "Сликај",
    retry: "Повторно",
    eventExpiredTitle: "Настанот е истечен",
    eventExpiredMsg: "Пристапот до овој настан е завршен. Контактирајте го организаторот.",
    goHome: "Оди на почетна",
    adminModeExpired: "Админ режим: Преглед на истечен настан",
    unknownUser: "Непознат корисник",
    authErrorFill: "Ве молиме пополнете ги сите полиња",
    authErrorEmail: "Оваа е-пошта е веќе регистрирана",
    authErrorInvalid: "Невалидни податоци. Обидете се повторно.",
    linkCopied: "Линкот е копиран!",
    salesContactMsg: "Ви благодариме! Нашиот тим ќе ве контактира.",
    adminSettings: "Админ: Истекување",
    customDuration: "Прилагодено",
    iAmPhotographer: "Јас сум фотограф / студио",
    studioName: "Име на студио / бизнис",
    studioDashboard: "Студио табла",
    verifiedStudio: "Верификувано студио",
    downloadAll: "Превземи се",
    views: "Прегледи",
    watermark: "Додади воден жиг",
    watermarkApplied: "Водениот жиг ќе биде применет",
    applyWatermark: "Примени воден жиг",
    storageLimit: "Достигнат лимит на меморија!",
    videoRestricted: "Видео прикачување е достапно за Pro и Studio.",
    upgradeToUpload: "Надградете за повеќе",
    setCover: "Постави како насловна",
    coverSet: "Насловната е ажурирана!",
    contactSalesTitle: "Контактирајте за надградба",
    contactSalesDesc: "За да го отклучите ова ниво, контактирајте не. Админ ќе го надгради вашиот профил.",
    openWhatsapp: "Отвори WhatsApp",
    openEmail: "Испрати е-пошта",
    downloading: "Се креира ZIP...",
    downloadReady: "Превземи",
    zipError: "Грешка при креирање ZIP",
    slideshow: "Слајдшоу",
    exitSlideshow: "Излези",
    play: "Пушти",
    pause: "Пауза",
    studioSettings: "Студио подесувања",
    uploadLogo: "Прикачи лого/потпис",
    logoDesc: "Прикачете PNG со транспарентна позадина. Ова ќе се примени на сите фотографии.",
    currentLogo: "Тековно лого",
    removeLogo: "Избриши лого",
    saveSettings: "Зачувај",
    opacity: "Проѕирност",
    size: "Големина",
    preview: "Преглед на жиг",
    position: "Позиција",
    offsetX: "Хоризонтално поместување",
    offsetY: "Вертикално поместување",
    topLeft: "Горе Лево",
    topRight: "Горе Десно",
    bottomLeft: "Долу Лево",
    bottomRight: "Долу Десно",
    center: "Центар",
    guestbook: "Книга на гости",
    leaveMessage: "Остави порака...",
    signGuestbook: "Потпиши се",
    noMessages: "Нема пораки. Биди прв!",
    messageSent: "Пораката е испратена!",
    pinRequired: "Потребен е PIN",
    enterPin: "Внесете PIN",
    submitPin: "Отклучи",
    optionalPin: "Опционален PIN код",
    pinDesc: "Оставете празно за јавен пристап",
    invalidPin: "Неточен PIN",
    findMe: "Најди ме",
    findMeTitle: "Најди ме со AI",
    findMeDesc: "Прикачете селфи и ние ќе ги означиме вашите слики.",
    uploadSelfie: "Сликај селфи",
    scanning: "Скенирање...",
    noFaceDetected: "Не е детектирано лице.",
    foundMatches: "Пронајдени совпаѓања",
    noMatchesFound: "Не се пронајдени фотографии.",
    clearFilter: "Исчисти филтер",
    processing: "Се процесира видео...",
    switchCamera: "Смени камера"
  },
  tr: {
    appName: "SnapifY",
    heroTitlePrefix: "Partile.",
    heroTitleSuffix: "Anında Çek.",
    heroDesc: "Doğum günleri, düğünler ve partiler için saniyeler içinde paylaşılan albümler oluşturun. Misafirlerinizin büyüyü yakalamasına izin verin.",
    getStarted: "Başlayın",
    adminDemo: "Yönetici Demo",
    signIn: "Giriş Yap",
    signUp: "Kayıt Ol",
    fullName: "Ad Soyad",
    email: "E-posta Adresi",
    password: "Şifre",
    createAccount: "Hesap Oluştur",
    continueGoogle: "Google ile Devam Et",
    terms: "Devam ederek, Şartlar ve Koşulları kabul etmiş olursunuz",
    pricingTitle: "Basit, Şeffaf Fiyatlandırma",
    bestValue: "En İyi Değer",
    forProfessionals: "Profesyoneller İçin",
    event: "etkinlik",
    currentPlan: "Mevcut Plan",
    contactSales: "Satış ile İletişim",
    startFree: "Ücretsiz Başla",
    myEvents: "Etkinliklerim",
    manageEvents: "Partilerinizi ve albümlerinizi yönetin",
    newEvent: "Yeni Etkinlik",
    noEvents: "Henüz etkinlik yok",
    createFirst: "Arkadaşlarınızla anı yakalamak için ilk etkinliğinizi oluşturun!",
    createNow: "Şimdi etkinlik oluştur",
    dateTBD: "Tarih Belirlenecek",
    memories: "anılar",
    owner: "Sahip",
    expired: "Süresi Doldu",
    active: "Aktif",
    forever: "Sonsuza Dek",
    copyLink: "Bağlantıyı Kopyala",
    hostedBy: "Ev Sahibi",
    gallery: "Galeri",
    noPhotos: "Henüz fotoğraf yok",
    beFirst: "İlk fotoğrafı çeken siz olun!",
    snap: "Çek",
    upload: "Yükle",
    joinParty: "Partiye Katıl",
    enterName: "Fotoğraf yüklemek için adınızı girin",
    yourName: "Adınız",
    continue: "Devam Et",
    cancel: "İptal",
    createEvent: "Yeni Etkinlik Oluştur",
    eventTitle: "Etkinlik Başlığı",
    eventTheme: "Etkinlik Teması",
    eventDate: "Etkinlik Tarihi",
    setDate: "Tarih Ayarla",
    aiDesc: "AI Açıklaması",
    autoGenerate: "Otomatik Oluştur",
    generating: "Oluşturuluyor...",
    aiPlaceholder: "AI'ın eğlenceli bir açıklama yazması için tıklayın...",
    createParty: "Parti Oluştur",
    guest: "Misafir",
    logOut: "Çıkış Yap",
    home: "Ana Sayfa",
    adminDashboard: "SnapifY Yönetici",
    masterControl: "Ana Kontrol Paneli",
    users: "Kullanıcılar",
    events: "Etkinlikler",
    exit: "Çıkış",
    totalUsers: "Toplam Kullanıcı",
    totalEvents: "Toplam Etkinlik",
    totalMedia: "Toplam Medya",
    storage: "Depolama",
    registeredUsers: "Kayıtlı Kullanıcılar",
    tier: "Seviye",
    actions: "İşlemler",
    deleteUserConfirm: "Bu kullanıcıyı ve tüm verilerini silmek istediğinizden emin misiniz?",
    storageUsage: "Kullanıcı Depolama Kullanımı",
    systemEvents: "Sistem Etkinlikleri",
    host: "Ev Sahibi",
    status: "Durum",
    mediaCount: "Medya Sayısı",
    items: "öğe",
    noDate: "Tarih Yok",
    exp: "Bitiş",
    unlimited: "Sınırsız",
    editEvent: "Etkinliği Düzenle",
    modifyExpiration: "Süreyi Değiştir",
    neverExpires: "Asla Sona Ermez",
    expireImmediately: "Hemen Sona Erdir",
    setNewDuration: "Yeni Süre Belirle",
    saveChanges: "Değişiklikleri Kaydet",
    modifyExpirationNote: "Süreyi değiştirmek, kaydettiğiniz andan itibaren zamanlayıcıyı sıfırlar.",
    seconds: "Saniye",
    minutes: "Dakika",
    hours: "Saat",
    days: "Gün",
    managing: "Yönetiliyor",
    mediaItems: "medya öğesi",
    noMedia: "Bu etkinlikte medya yok",
    deleteMediaConfirm: "Bu öğeyi sil?",
    deleteEventConfirm: "Bu etkinliği kalıcı olarak sil?",
    cameraError: "Kameraya erişilemiyor. İzinleri kontrol edin.",
    takePhoto: "Fotoğraf Çek",
    retry: "Tekrar Dene",
    eventExpiredTitle: "Etkinlik Sona Erdi",
    eventExpiredMsg: "Bu etkinliğe erişim süresi doldu. Daha fazla bilgi için organizatörle iletişime geçin.",
    goHome: "Ana Sayfaya Git",
    adminModeExpired: "Yönetici Modu: Süresi Dolmuş Etkinlik",
    unknownUser: "Bilinmeyen Kullanıcı",
    authErrorFill: "Lütfen tüm alanları doldurun",
    authErrorEmail: "Bu e-posta zaten kayıtlı",
    authErrorInvalid: "Geçersiz bilgiler. Tekrar deneyin.",
    linkCopied: "Bağlantı panoya kopyalandı!",
    salesContactMsg: "İlginiz için teşekkürler! Satış ekibimiz sizinle iletişime geçecek.",
    adminSettings: "Yönetici Ayarları: Süre",
    customDuration: "Özel Süre",
    iAmPhotographer: "Ben Bir Fotoğrafçıyım / Stüdyoyum",
    studioName: "Stüdyo / İşletme Adı",
    studioDashboard: "Stüdyo Paneli",
    verifiedStudio: "Onaylı Stüdyo",
    downloadAll: "Tümünü İndir",
    views: "Görüntüleme",
    watermark: "Filigran Ekle",
    watermarkApplied: "Filigran uygulanacak",
    applyWatermark: "Filigran Uygula",
    storageLimit: "Depolama Sınırına Ulaşıldı!",
    videoRestricted: "Video yüklemeleri Pro ve Studio planlarında mevcuttur.",
    upgradeToUpload: "Yüklemek için Yükselt",
    setCover: "Kapak Olarak Ayarla",
    coverSet: "Kapak güncellendi!",
    contactSalesTitle: "Yükseltmek için İletişime Geçin",
    contactSalesDesc: "Bu seviyenin kilidini açmak için lütfen bizimle iletişime geçin. Bir yönetici hesabınızı yükseltecektir.",
    openWhatsapp: "WhatsApp'ı Aç",
    openEmail: "E-posta Gönder",
    downloading: "Sıkıştırılıyor...",
    downloadReady: "İndirme Hazır",
    zipError: "ZIP hatası",
    slideshow: "Slayt Gösterisi",
    exitSlideshow: "Çık",
    play: "Oynat",
    pause: "Duraklat",
    studioSettings: "Stüdyo Ayarları",
    uploadLogo: "Logo/İmza Yükle",
    logoDesc: "En iyi sonuç için şeffaf arka planlı PNG yükleyin. Tüm fotoğrafların sağ alt köşesine uygulanacaktır.",
    currentLogo: "Mevcut Logo",
    removeLogo: "Logoyu Kaldır",
    saveSettings: "Ayarları Kaydet",
    opacity: "Opaklık",
    size: "Boyut",
    preview: "Filigran Önizleme",
    position: "Pozisyon",
    offsetX: "Yatay Ofset",
    offsetY: "Dikey Ofset",
    topLeft: "Sol Üst",
    topRight: "Sağ Üst",
    bottomLeft: "Sol Alt",
    bottomRight: "Sağ Alt",
    center: "Orta",
    guestbook: "Ziyaretçi Defteri",
    leaveMessage: "Mesaj bırakın...",
    signGuestbook: "İmzala",
    noMessages: "Henüz mesaj yok. İlk siz olun!",
    messageSent: "Mesaj gönderildi!",
    pinRequired: "PIN Gerekli",
    enterPin: "Etkinlik PIN'ini Girin",
    submitPin: "Etkinliği Aç",
    optionalPin: "İsteğe Bağlı PIN Kodu",
    pinDesc: "Herkese açık erişim için boş bırakın",
    invalidPin: "Hatalı PIN",
    findMe: "Beni Bul",
    findMeTitle: "AI ile Beni Bul",
    findMeDesc: "Bir selfie yükleyin ve bu galerideki fotoğraflarınızı vurgulayalım.",
    uploadSelfie: "Selfie Çek",
    scanning: "Galeri Taranıyor...",
    noFaceDetected: "Yüz algılanamadı. Tekrar deneyin.",
    foundMatches: "Eşleşmeler Bulundu",
    noMatchesFound: "Henüz fotoğrafınız bulunamadı.",
    clearFilter: "Filtreyi Temizle",
    processing: "Video İşleniyor...",
    switchCamera: "Kamerayı Değiştir"
  },
  sq: {
    appName: "SnapifY",
    heroTitlePrefix: "Festo Fort.",
    heroTitleSuffix: "Shkrep Tani.",
    heroDesc: "Krijoni albume të përbashkëta për ditëlindje, dasma dhe festa në sekonda. Lejoni mysafirët tuaj të kapin magjinë.",
    getStarted: "Fillo Tani",
    adminDemo: "Demo Admin",
    signIn: "Hyni",
    signUp: "Regjistrohu",
    fullName: "Emri i Plotë",
    email: "Adresa Email",
    password: "Fjalëkalimi",
    createAccount: "Krijo Llogari",
    continueGoogle: "Vazhdo me Google",
    terms: "Duke vazhduar, ju pajtoheni me Kushtet tona",
    pricingTitle: "Çmime të Thjeshta",
    bestValue: "Vlera më e mirë",
    forProfessionals: "Për Profesionistët",
    event: "ngjarje",
    currentPlan: "Plani Aktual",
    contactSales: "Kontakto Shitjet",
    startFree: "Fillo Falas",
    myEvents: "Ngjarjet e Mia",
    manageEvents: "Menaxho festat dhe albumet e tua",
    newEvent: "Ngjarje e Re",
    noEvents: "Ende asnjë ngjarje",
    createFirst: "Krijo ngjarjen tënde të parë!",
    createNow: "Krijo ngjarje tani",
    dateTBD: "Data së shpejti",
    memories: "kujtime",
    owner: "Pronari",
    expired: "Skaduar",
    active: "Aktive",
    forever: "Përgjithmonë",
    copyLink: "Kopjo Linkun",
    hostedBy: "Organizuar nga",
    gallery: "Galeria",
    noPhotos: "Asnjë foto ende",
    beFirst: "Bëhu i pari që shkrep një moment!",
    snap: "Shkrep",
    upload: "Ngarko",
    joinParty: "Bashkohu në Festë",
    enterName: "Shkruani emrin tuaj për të ngarkuar foto",
    yourName: "Emri Juaj",
    continue: "Vazhdo",
    cancel: "Anulo",
    createEvent: "Krijo Ngjarje të Re",
    eventTitle: "Titulli i Ngjarjes",
    eventTheme: "Tema e Ngjarjes",
    eventDate: "Data e Ngjarjes",
    setDate: "Cakto Datën",
    aiDesc: "Përshkrim AI",
    autoGenerate: "Gjenero",
    generating: "Po gjenerohet...",
    aiPlaceholder: "Kliko për të gjeneruar një përshkrim...",
    createParty: "Krijo Festë",
    guest: "Mysafir",
    logOut: "Dil",
    home: "Kreu",
    adminDashboard: "SnapifY Admin",
    masterControl: "Paneli Kryesor i Kontrollit",
    users: "Përdoruesit",
    events: "Ngjarjet",
    exit: "Dalja",
    totalUsers: "Gjithsej Përdorues",
    totalEvents: "Gjithsej Ngjarje",
    totalMedia: "Gjithsej Media",
    storage: "Hapësira",
    registeredUsers: "Përdoruesit e Regjistruar",
    tier: "Niveli",
    actions: "Veprime",
    deleteUserConfirm: "A jeni të sigurt që doni ta fshini këtë përdorues?",
    storageUsage: "Përdorimi i Hapësirës",
    systemEvents: "Ngjarjet e Sistemit",
    host: "Mikpritësi",
    status: "Statusi",
    mediaCount: "Numri i Mediave",
    items: "artikuj",
    noDate: "Pa Datë",
    exp: "Skadon",
    unlimited: "Pa limit",
    editEvent: "Ndrysho Ngjarjen",
    modifyExpiration: "Ndrysho Skadimin",
    neverExpires: "Nuk Skadon Kurrë",
    expireImmediately: "Skado Menjëherë",
    setNewDuration: "Cakto Kohëzgjatje të Re",
    saveChanges: "Ruaj Ndryshimet",
    modifyExpirationNote: "Ndryshimi i skadimit do të rifillojë kohëmatësin.",
    seconds: "Sekonda",
    minutes: "Minuta",
    hours: "Orë",
    days: "Ditë",
    managing: "Duke menaxhuar",
    mediaItems: "artikuj media",
    noMedia: "Asnjë media në këtë ngjarje",
    deleteMediaConfirm: "Fshi këtë artikull?",
    deleteEventConfirm: "Fshi këtë ngjarje përgjithmonë?",
    cameraError: "Nuk mund të qaset kamera.",
    takePhoto: "Bëj Foto",
    retry: "Provo Përsëri",
    eventExpiredTitle: "Ngjarja ka Skaduar",
    eventExpiredMsg: "Qasja në këtë ngjarje ka përfunduar.",
    goHome: "Shko në Kreu",
    adminModeExpired: "Admin: Po shikon ngjarje të skaduar",
    unknownUser: "Përdorues i Panjohur",
    authErrorFill: "Ju lutemi plotësoni të gjitha fushat",
    authErrorEmail: "Kjo email është regjistruar tashmë",
    authErrorInvalid: "Të dhëna të pasakta. Provo përsëri.",
    linkCopied: "Linku u kopjua!",
    salesContactMsg: "Faleminderit! Ekipi ynë do t'ju kontaktojë.",
    adminSettings: "Cilësimet Admin: Skadimi",
    customDuration: "Kohëzgjatje e Veçantë",
    iAmPhotographer: "Jam Fotograf / Studio",
    studioName: "Emri i Studios / Biznesit",
    studioDashboard: "Paneli i Studios",
    verifiedStudio: "Studio e Verifikuar",
    downloadAll: "Shkarko Të Gjitha",
    views: "Shikime",
    watermark: "Apliko Watermark",
    watermarkApplied: "Watermark do të aplikohet",
    applyWatermark: "Apliko Watermark",
    storageLimit: "Kufiri i Hapësirës u Arrit!",
    videoRestricted: "Videot janë vetëm për planet Pro dhe Studio.",
    upgradeToUpload: "Përmirëso për të Ngarkuar",
    setCover: "Cakto si Kopertinë",
    coverSet: "Kopertina u përditësua!",
    contactSalesTitle: "Kontaktoni Shitjet për Përmirësim",
    contactSalesDesc: "Për të zhbllokuar këtë nivel, kontaktoni. Një administrator do ta përmirësojë llogarinë tuaj.",
    openWhatsapp: "Hap WhatsApp",
    openEmail: "Dërgo Email",
    downloading: "Po krijon ZIP...",
    downloadReady: "Gati për Shkarkim",
    zipError: "Gabim në krijimin e ZIP",
    slideshow: "Slideshow",
    exitSlideshow: "Dil",
    play: "Luaj",
    pause: "Pusho",
    studioSettings: "Cilësimet e Studios",
    uploadLogo: "Ngarko Logo/Nënshkrim",
    logoDesc: "Ngarkoni një PNG me sfond transparent. Do të vendoset në cepin e djathtë poshtë.",
    currentLogo: "Logo Aktuale",
    removeLogo: "Fshi Logo",
    saveSettings: "Ruaj Cilësimet",
    opacity: "Opaciteti",
    size: "Madhësia",
    preview: "Pamje paraprake",
    position: "Pozicioni",
    offsetX: "Zhvendosje Horizontale",
    offsetY: "Zhvendosje Vertikale",
    topLeft: "Lart Majtas",
    topRight: "Lart Djathtas",
    bottomLeft: "Poshtë Majtas",
    bottomRight: "Poshtë Djathtas",
    center: "Qendër",
    guestbook: "Libri i Mysafirëve",
    leaveMessage: "Lini një mesazh...",
    signGuestbook: "Nënshkruaj",
    noMessages: "Asnjë mesazh ende. Bëhu i pari!",
    messageSent: "Mesazhi u dërgua!",
    pinRequired: "Kërkohet PIN",
    enterPin: "Shkruani PIN-in",
    submitPin: "Zhblloko",
    optionalPin: "Kodi PIN Opsional",
    pinDesc: "Lëreni bosh për qasje publike",
    invalidPin: "PIN i Gabuar",
    findMe: "Më Gjej",
    findMeTitle: "Më Gjej me AI",
    findMeDesc: "Ngarkoni një selfie dhe do të gjejmë fotot tuaja.",
    uploadSelfie: "Bëj Selfie",
    scanning: "Po skanon galerinë...",
    noFaceDetected: "Nuk u gjet fytyrë. Provo përsëri.",
    foundMatches: "U Gjetën",
    noMatchesFound: "Asnjë foto e juaja ende.",
    clearFilter: "Pastro",
    processing: "Duke procesuar videon...",
    switchCamera: "Ndrysho Kamerën"
  }
};

export const getPricingTiers = (t: TranslateFn): PricingTier[] => [
  {
    id: TierLevel.FREE,
    name: 'Party Starter',
    price: 'Free',
    features: ['7 Hours Access Limit', '100MB Storage', 'Standard Support', 'Ad-supported'],
    cta: t('startFree'),
    limit: '7 Hours Active Time'
  },
  {
    id: TierLevel.BASIC,
    name: 'Celebration Plus',
    price: '$9.99',
    features: ['10GB Storage', '30 Days Active', 'HD Photo Uploads', 'AI Auto-Captioning'],
    cta: t('contactSales'),
    limit: '30 Days Access'
  },
  {
    id: TierLevel.PRO,
    name: 'Gala Elite',
    price: '$29.99',
    features: ['30GB Storage', '30 Days Active', '4K Video Support', 'Priority Support', 'Custom Branding'],
    cta: t('contactSales'),
    limit: '30 Days Access'
  },
  {
    id: TierLevel.STUDIO,
    name: 'Studio Enterprise',
    price: '$99',
    features: ['Unlimited Events', 'Auto Watermarking', 'Studio Branding', 'Client Analytics', 'Instant ZIP Download'],
    cta: t('contactSales'),
    limit: 'Professional Suite'
  }
];

export const EVENT_THEMES = [
  { id: 'Birthday', label: 'Birthday', emoji: '🎂' },
  { id: 'Wedding', label: 'Wedding', emoji: '💍' },
  { id: 'Party', label: 'Party', emoji: '🎉' },
  { id: 'Trip', label: 'Trip', emoji: '✈️' },
  { id: 'Other', label: 'Other', emoji: '✨' },
];

export const HERO_IMAGES = [
  "https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&q=80&w=1920", 
  "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&q=80&w=1920", 
  "https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?auto=format&fit=crop&q=80&w=1920", 
  "https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&q=80&w=1920", 
  "https://images.unsplash.com/photo-1544531586-fde5298cdd40?auto=format&fit=crop&q=80&w=1920"
];
